import { useState, useEffect, useCallback, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { ChevronRight, ChevronLeft, X, Sparkles, Play } from 'lucide-react';
import clsx from 'clsx';

const TOUR_DONE_KEY = 'agentops-tour-done';

const STEPS = [
  {
    title: 'These are real PRs',
    body: 'Each row is a pull request that flowed through all four AI agents. The decision badge (AUTO/BLOCK/CHANGES), score, and findings come from real agent runs against AWS DynamoDB.',
    targetSelector: '[data-tour="pipelines-table"]',
    placement: 'top',
    route: '/dashboard/pipelines',
    cta: 'Now I\'ll click into one of these →',
  },
  {
    title: 'Agent decisions, scored and explained',
    body: 'Every PR gets a 6-axis quality score (Security · Quality · Performance · Architecture · Test Impact · Documentation) from ReviewAgent. Findings are sorted by severity with code snippets and AI-suggested fixes.',
    targetSelector: '[data-tour="pipeline-detail"]',
    placement: 'center',
    route: null, // computed dynamically based on pipelines
    cta: 'Now let\'s see incident response →',
  },
  {
    title: 'AI-powered incident response',
    body: 'IncidentAgent uses Z-score detection on a rolling baseline. When anomalies fire, Gemini hypothesizes root causes with confidence ratings. Look at the violet AI Analysis panel — that hypothesis was generated by Gemini in real time.',
    targetSelector: '[data-tour="incidents-page"]',
    placement: 'top',
    route: '/dashboard/incidents',
    cta: 'Finish tour',
  },
];

export default function Tour() {
  const [active, setActive] = useState(false);
  const [stepIdx, setStepIdx] = useState(0);
  const [targetRect, setTargetRect] = useState(null);
  const navigate = useNavigate();
  const location = useLocation();
  const tourStartedRef = useRef(false);

  // Show the "Start tour" floating button if tour hasn't been completed
  const tourDone = typeof window !== 'undefined' && localStorage.getItem(TOUR_DONE_KEY) === '1';

  const finishTour = useCallback(() => {
    setActive(false);
    setStepIdx(0);
    setTargetRect(null);
    tourStartedRef.current = false;
    localStorage.setItem(TOUR_DONE_KEY, '1');
  }, []);

  const startTour = useCallback(() => {
    setActive(true);
    setStepIdx(0);
    tourStartedRef.current = true;
    // Navigate to first step's route if not already there
    if (location.pathname !== STEPS[0].route) {
      navigate(STEPS[0].route);
    }
  }, [location.pathname, navigate]);

  const goToStep = useCallback(async (idx) => {
    if (idx >= STEPS.length) {
      finishTour();
      return;
    }
    const step = STEPS[idx];
    setStepIdx(idx);
    setTargetRect(null);

    // Handle dynamic route for step 1 (pipeline detail) — pick first available
    if (idx === 1) {
      // Look for first pipeline row link
      const firstRow = document.querySelector('[data-tour="pipelines-table"] a, [data-tour="pipelines-table"] [data-pipeline-id]');
      if (firstRow) {
        const href = firstRow.getAttribute('href');
        if (href) {
          navigate(href);
          return;
        }
      }
      // Fallback: try to query the API
      try {
        const res = await fetch('/api/pipelines?limit=1');
        const data = await res.json();
        const first = data.items?.[0];
        if (first?.pipeline_id) {
          navigate(`/dashboard/pipelines/${encodeURIComponent(first.pipeline_id)}`);
          return;
        }
      } catch {
        // ignore, stay on current page
      }
    }

    if (step.route && location.pathname !== step.route) {
      navigate(step.route);
    }
  }, [finishTour, navigate, location.pathname]);

  // Track target element rect after step changes + route loads
  useEffect(() => {
    if (!active) return;
    const step = STEPS[stepIdx];
    if (!step) return;

    let pollCount = 0;
    const maxPolls = 30; // ~3 seconds at 100ms

    const poll = () => {
      const el = document.querySelector(step.targetSelector);
      if (el) {
        const rect = el.getBoundingClientRect();
        setTargetRect({
          top: rect.top + window.scrollY,
          left: rect.left + window.scrollX,
          width: rect.width,
          height: rect.height,
        });
        return;
      }
      pollCount++;
      if (pollCount < maxPolls) {
        setTimeout(poll, 100);
      } else {
        // Target not found — show tooltip centered anyway
        setTargetRect(null);
      }
    };

    // Wait a bit for route transition + data load
    const timer = setTimeout(poll, 250);
    return () => clearTimeout(timer);
  }, [active, stepIdx, location.pathname]);

  // Recompute rect on resize/scroll
  useEffect(() => {
    if (!active || !targetRect) return;
    const recompute = () => {
      const step = STEPS[stepIdx];
      const el = document.querySelector(step.targetSelector);
      if (el) {
        const rect = el.getBoundingClientRect();
        setTargetRect({
          top: rect.top + window.scrollY,
          left: rect.left + window.scrollX,
          width: rect.width,
          height: rect.height,
        });
      }
    };
    window.addEventListener('resize', recompute);
    window.addEventListener('scroll', recompute, true);
    return () => {
      window.removeEventListener('resize', recompute);
      window.removeEventListener('scroll', recompute, true);
    };
  }, [active, stepIdx, targetRect]);

  // Floating button when tour isn't active
  if (!active) {
    return (
      <button
        onClick={startTour}
        className={clsx(
          'fixed bottom-6 right-6 z-40 flex items-center gap-2 px-4 py-2.5 rounded-full',
          'bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium',
          'shadow-lg shadow-emerald-900/40 transition-all',
          !tourDone && 'animate-pulse-slow ring-2 ring-emerald-400/40 ring-offset-2 ring-offset-slate-950',
        )}
        title="Take the guided tour"
      >
        <Play className="w-3.5 h-3.5 fill-white" />
        {tourDone ? 'Replay tour' : 'Take the tour'}
      </button>
    );
  }

  const step = STEPS[stepIdx];

  return (
    <>
      {/* Backdrop with cutout */}
      <div className="fixed inset-0 z-40 pointer-events-none">
        {targetRect ? (
          <svg width="100%" height="100%" className="absolute inset-0">
            <defs>
              <mask id="tour-mask">
                <rect width="100%" height="100%" fill="white" />
                <rect
                  x={targetRect.left - 8}
                  y={targetRect.top - 8 - window.scrollY}
                  width={targetRect.width + 16}
                  height={targetRect.height + 16}
                  fill="black"
                  rx="8"
                />
              </mask>
            </defs>
            <rect width="100%" height="100%" fill="rgba(2, 6, 23, 0.75)" mask="url(#tour-mask)" />
            <rect
              x={targetRect.left - 8}
              y={targetRect.top - 8 - window.scrollY}
              width={targetRect.width + 16}
              height={targetRect.height + 16}
              fill="none"
              stroke="#10b981"
              strokeWidth="2"
              rx="8"
              className="animate-pulse-slow"
            />
          </svg>
        ) : (
          <div className="absolute inset-0 bg-slate-950/75" />
        )}
      </div>

      {/* Tooltip card */}
      <div
        className="fixed z-50 pointer-events-auto"
        style={getTooltipPosition(targetRect, step.placement)}
      >
        <div className="w-[400px] max-w-[calc(100vw-2rem)] bg-slate-900 border border-emerald-700 rounded-lg shadow-2xl">
          {/* Header */}
          <div className="px-5 py-3 border-b border-slate-800 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-400" />
              <span className="text-[10px] uppercase tracking-widest text-slate-500">
                step {stepIdx + 1} of {STEPS.length}
              </span>
            </div>
            <button onClick={finishTour} className="text-slate-500 hover:text-slate-300 transition-colors">
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Body */}
          <div className="px-5 py-4">
            <h3 className="text-base font-semibold text-slate-100 mb-2">{step.title}</h3>
            <p className="text-sm text-slate-300 leading-relaxed">{step.body}</p>
          </div>

          {/* Progress dots */}
          <div className="px-5 py-2 flex items-center gap-1.5">
            {STEPS.map((_, i) => (
              <div
                key={i}
                className={clsx(
                  'h-1 rounded-full transition-all',
                  i === stepIdx ? 'w-8 bg-emerald-500' : i < stepIdx ? 'w-4 bg-emerald-700' : 'w-4 bg-slate-700',
                )}
              />
            ))}
          </div>

          {/* Footer */}
          <div className="px-5 py-3 border-t border-slate-800 flex items-center justify-between">
            <button
              onClick={finishTour}
              className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
            >
              Skip tour
            </button>
            <div className="flex items-center gap-2">
              {stepIdx > 0 && (
                <button
                  onClick={() => goToStep(stepIdx - 1)}
                  className="flex items-center gap-1 px-3 py-1.5 rounded-md text-xs text-slate-300 hover:bg-slate-800 transition-colors"
                >
                  <ChevronLeft className="w-3.5 h-3.5" />
                  Back
                </button>
              )}
              <button
                onClick={() => goToStep(stepIdx + 1)}
                className="flex items-center gap-1.5 px-4 py-1.5 rounded-md bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium transition-colors"
              >
                {stepIdx === STEPS.length - 1 ? 'Finish' : 'Next'}
                {stepIdx < STEPS.length - 1 && <ChevronRight className="w-3.5 h-3.5" />}
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// Decide where to render the tooltip relative to the highlighted element
function getTooltipPosition(targetRect, placement) {
  if (!targetRect || placement === 'center') {
    // Center on screen
    return {
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
    };
  }

  const PADDING = 16;
  const TOOLTIP_HEIGHT = 280; // approximate
  const TOOLTIP_WIDTH = 400;

  // Default: place below the target
  const viewportTop = targetRect.top - window.scrollY;
  const spaceBelow = window.innerHeight - (viewportTop + targetRect.height);

  let top, left, transform = '';

  if (placement === 'top' || spaceBelow < TOOLTIP_HEIGHT + PADDING) {
    // Place above
    top = viewportTop - TOOLTIP_HEIGHT - PADDING;
    if (top < PADDING) top = PADDING; // Don't go off the top
  } else {
    // Place below
    top = viewportTop + targetRect.height + PADDING;
  }

  // Horizontal: center under target, but clamp to viewport
  left = targetRect.left + targetRect.width / 2 - TOOLTIP_WIDTH / 2;
  if (left < PADDING) left = PADDING;
  if (left + TOOLTIP_WIDTH > window.innerWidth - PADDING) {
    left = window.innerWidth - TOOLTIP_WIDTH - PADDING;
  }

  return { top: `${top}px`, left: `${left}px`, transform };
}